version: '3.3'

services:
  search-db:
    container_name: search-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - picsure-search:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - POSTGRES_PASSWORD=foo
      - POSTGRES_USER=picsure
      - POSTGRES_DB=search
volumes:
  picsure-search: