version: '3.3'

services:
  dictionary-db:
    container_name: dictionary-db
    image: postgres:16-alpine
    volumes:
      - $DOCKER_CONFIG_DIR/dictionary/db/data:/var/lib/postgresql/data
      - $DOCKER_CONFIG_DIR/dictionary/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    env_file: .env
    restart: always
    networks:
      - dictionary
  dictionary-api:
    container_name: dictionary-api
    image: avillach/dictionary-api:latest
    build: .
    depends_on:
      - dictionary-db
    restart: always
    env_file: .env
    networks:
      - dictionary
      - hpdsNet
      - picsure
  dictionary-dump:
    container_name: dictionary-dump
    image: avillach/dictionary-dump:latest
    build: ./aggregate
    depends_on:
      - dictionary-db
    restart: always
    env_file: .env
    volumes:
      - $DOCKER_CONFIG_DIR/dictionary/dump/application.properties:/application.properties
    networks:
      - dictionary
      - hpdsNet
      - picsure

volumes:
  picsure-search:

networks:
  dictionary:
    external: true
  picsure:
    external: true
  hpdsNet:
    external: true
