version: '3.3'

services:
  dictionary-db:
    container_name: dictionary-db
    image: postgres:16-alpine
    volumes:
      - picsure-search:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    env_file: .env
    networks:
      - dictionary
  dictionary-api:
    container_name: dictionary-api
    image: hmsdbmi-avl/uploader:1.0.0
    build: .
    depends_on:
      - dictionary-db
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - dictionary
      - hpdsNet
      - picsure

volumes:
  picsure-search:

networks:
  dictionary:
  picsure:
    external: true
  hpdsNet:
    external: true
